server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://acmaker.vip/mild_integrated_manage_system?useUnicode=true&amp;serverTimezone=GMT%2B8&amp;characterEncoding=UTF-8
    username: mildUser
    password: mildUser
mybatis:
  typeAliasesPackage: com.syousui.mildintegratedmanagesystem.pojo.po
  mapperLocations: classpath:mapper/*.xml
pagehelper:
  helperDialect: mysql
  reasonable: false
  params: count=countSql
  supportMethodsArguments: true
